name: first-github-action
on:
  push:
    branches:
      # When someone push to `main` branch
      - develop
jobs:
  write-to-console:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Hello world!'
