name: first-github-action
on:
  push:
    branches:
      # When someone push to `main` branch
      - main
jobs:
  
  # test:
  #   ...
  deploy:
    name: "Deploy to staging"
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    # needs: test
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
      
      - name: Checkout the repo on the Staging Server
        run: ssh staging 'git clone git@github.com:thezainuddin/nginx-certbot.git'
      
      - name: Start containers
        run: ssh staging 'cd nginx-certbot && docker-compose -f "docker-compose.yml" up -d'
        
      - name: Test the App
        run: |
          ssh staging 'if [ $( docker ps -a | grep tesapp_client_ | wc -l ) -gt 0 ]; then  echo "testContainer exists"; else   echo "testContainer does not exist" && raise error; fi'

      - name: Remove the workspace
        run: ssh staging 'rm -rf nginx-certbot/'
